/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminForm.java
 *
 * Created on Mar 16, 2010, 4:18:00 AM
 */
package arms;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author vh4x0r
 */
public class AdminForm extends javax.swing.JFrame {

    /** Creates new form AdminForm */
    public AdminForm(ArrayList<Teacher> teachers, ArrayList<Subject> subjects) {
        this.teachers = teachers;
        this.subjects = subjects;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminTabbedPane = new javax.swing.JTabbedPane();
        teacherPanel = new javax.swing.JPanel();
        teacherScrollPane = new javax.swing.JScrollPane();
        teacherList = new javax.swing.JList();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        downButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        deleteTeacherButton = new javax.swing.JButton();
        passwdButton = new javax.swing.JButton();
        addTeacherButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        subPanel = new javax.swing.JPanel();
        subScrollPane = new javax.swing.JScrollPane();
        subList = new javax.swing.JList();
        subLabel = new javax.swing.JLabel();
        subIdLabel = new javax.swing.JLabel();
        addSubButton = new javax.swing.JButton();
        deleteSubButton = new javax.swing.JButton();
        subTextField = new javax.swing.JTextField();
        subIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getResourceMap(AdminForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        adminTabbedPane.setToolTipText(resourceMap.getString("adminTabbedPane.toolTipText")); // NOI18N
        adminTabbedPane.setName("adminTabbedPane"); // NOI18N

        teacherPanel.setName("teacherPanel"); // NOI18N

        teacherScrollPane.setName("teacherScrollPane"); // NOI18N

        teacherList.setModel(new javax.swing.AbstractListModel() {
            Object[] strings = teachers.toArray();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        teacherList.setName("teacherList"); // NOI18N
        teacherList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                teacherListValueChanged(evt);
            }
        });
        teacherScrollPane.setViewportView(teacherList);

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        idLabel.setText(resourceMap.getString("idLabel.text")); // NOI18N
        idLabel.setName("idLabel"); // NOI18N

        loginLabel.setText(resourceMap.getString("loginLabel.text")); // NOI18N
        loginLabel.setName("loginLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getActionMap(AdminForm.class, this);
        downButton.setAction(actionMap.get("moveDown")); // NOI18N
        downButton.setText(resourceMap.getString("downButton.text")); // NOI18N
        downButton.setName("downButton"); // NOI18N

        upButton.setAction(actionMap.get("moveUp")); // NOI18N
        upButton.setText(resourceMap.getString("upButton.text")); // NOI18N
        upButton.setName("upButton"); // NOI18N

        deleteTeacherButton.setAction(actionMap.get("deleteTeacher")); // NOI18N
        deleteTeacherButton.setText(resourceMap.getString("deleteTeacherButton.text")); // NOI18N
        deleteTeacherButton.setName("deleteTeacherButton"); // NOI18N

        passwdButton.setText(resourceMap.getString("passwdButton.text")); // NOI18N
        passwdButton.setEnabled(false);
        passwdButton.setName("passwdButton"); // NOI18N

        addTeacherButton.setAction(actionMap.get("addTeacher")); // NOI18N
        addTeacherButton.setText(resourceMap.getString("addTeacherButton.text")); // NOI18N
        addTeacherButton.setName("addTeacherButton"); // NOI18N

        nameTextField.setEditable(false);
        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setBorder(null);
        nameTextField.setName("nameTextField"); // NOI18N

        idTextField.setEditable(false);
        idTextField.setText(resourceMap.getString("idTextField.text")); // NOI18N
        idTextField.setBorder(null);
        idTextField.setName("idTextField"); // NOI18N

        loginTextField.setEditable(false);
        loginTextField.setText(resourceMap.getString("loginTextField.text")); // NOI18N
        loginTextField.setBorder(null);
        loginTextField.setName("loginTextField"); // NOI18N

        javax.swing.GroupLayout teacherPanelLayout = new javax.swing.GroupLayout(teacherPanel);
        teacherPanel.setLayout(teacherPanelLayout);
        teacherPanelLayout.setHorizontalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teacherPanelLayout.createSequentialGroup()
                                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(upButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(downButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addTeacherButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(deleteTeacherButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                            .addComponent(passwdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(62, 62, 62))
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(teacherPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addGroup(teacherPanelLayout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        teacherPanelLayout.setVerticalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginLabel)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upButton)
                            .addComponent(addTeacherButton))
                        .addGap(18, 18, 18)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downButton)
                            .addComponent(deleteTeacherButton))
                        .addGap(18, 18, 18)
                        .addComponent(passwdButton))
                    .addComponent(teacherScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap())
        );

        adminTabbedPane.addTab(resourceMap.getString("teacherPanel.TabConstraints.tabTitle"), teacherPanel); // NOI18N

        subPanel.setToolTipText(resourceMap.getString("subPanel.toolTipText")); // NOI18N
        subPanel.setName("subPanel"); // NOI18N

        subScrollPane.setName("subScrollPane"); // NOI18N

        subList.setModel(new javax.swing.AbstractListModel() {
            Object[] strings = subjects.toArray();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subList.setName("subList"); // NOI18N
        subList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subListValueChanged(evt);
            }
        });
        subScrollPane.setViewportView(subList);

        subLabel.setText(resourceMap.getString("subLabel.text")); // NOI18N
        subLabel.setName("subLabel"); // NOI18N

        subIdLabel.setText(resourceMap.getString("subIdLabel.text")); // NOI18N
        subIdLabel.setName("subIdLabel"); // NOI18N

        addSubButton.setAction(actionMap.get("deleteSubject")); // NOI18N
        addSubButton.setText(resourceMap.getString("addSubButton.text")); // NOI18N
        addSubButton.setName("addSubButton"); // NOI18N

        deleteSubButton.setAction(actionMap.get("addSubject")); // NOI18N
        deleteSubButton.setText(resourceMap.getString("deleteSubButton.text")); // NOI18N
        deleteSubButton.setName("deleteSubButton"); // NOI18N

        subTextField.setEditable(false);
        subTextField.setText(resourceMap.getString("subTextField.text")); // NOI18N
        subTextField.setBorder(null);
        subTextField.setName("subTextField"); // NOI18N

        subIdTextField.setEditable(false);
        subIdTextField.setText(resourceMap.getString("subIdTextField.text")); // NOI18N
        subIdTextField.setBorder(null);
        subIdTextField.setName("subIdTextField"); // NOI18N

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(subLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(subIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addComponent(addSubButton)
                    .addComponent(deleteSubButton))
                .addContainerGap())
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subLabel)
                            .addComponent(subTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subIdLabel)
                            .addComponent(subIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(deleteSubButton)
                        .addGap(18, 18, 18)
                        .addComponent(addSubButton))
                    .addComponent(subScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap())
        );

        adminTabbedPane.addTab(resourceMap.getString("subPanel.TabConstraints.tabTitle"), subPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void dispose() {
        ARMSApp.getApplication().getMainFrame().setVisible(true);
        super.dispose();
    }

    @Action
    public void addTeacher() {
        String name = JOptionPane.showInputDialog(null, "Enter teacher name :", "Name", JOptionPane.QUESTION_MESSAGE);
        if (name.isEmpty()) {
            return;
        }
        String id = JOptionPane.showInputDialog(null, "Enter teacher id :", "ID", JOptionPane.QUESTION_MESSAGE);
        if (id.isEmpty()) {
            return;
        }
        String pass = JOptionPane.showInputDialog(null, "Enter password :", "Password", JOptionPane.QUESTION_MESSAGE);
        if (pass.isEmpty()) {
            return;
        }
        Teacher t = new Teacher(name, id, pass);
        teachers.add(t);
        teacherList.setListData(teachers.toArray());
    }

    @Action
    public void deleteTeacher() {
        int index = teacherList.getSelectedIndex();
        if (JOptionPane.showConfirmDialog(null, "Delete teacher ?", "Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            teachers.remove(index);
            teacherList.setListData(teachers.toArray());
        }
    }

    @Action
    public void moveUp() {
        int index = teacherList.getSelectedIndex();
        Teacher temp = teachers.get(index - 1);
        teachers.set(index - 1, teachers.get(index));
        teachers.set(index, temp);
        teacherList.setListData(teachers.toArray());
    }

    @Action
    public void moveDown() {
        int index = teacherList.getSelectedIndex();
        Teacher temp = teachers.get(index + 1);
        teachers.set(index + 1, teachers.get(index));
        teachers.set(index, temp);
        teacherList.setListData(teachers.toArray());
    }

    @Action
    public void addSubject() {
        String name = JOptionPane.showInputDialog("Enter name :");
        if (name.isEmpty()) {
            return;
        }
        String id = JOptionPane.showInputDialog("Enter subject id :");
        if (id.isEmpty()) {
            return;
        }
        Subject s = new Subject(name, id);
        subjects.add(s);
        subList.setListData(subjects.toArray());
    }

    @Action
    public void deleteSubject() {
        int index = subList.getSelectedIndex();
        if (JOptionPane.showConfirmDialog(null, "Delete subject ?", "Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            subjects.remove(index);
        }
        subList.setListData(subjects.toArray());
    }

    private void teacherListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_teacherListValueChanged
        // TODO add your handling code here:
        int selectIndex = teacherList.getSelectedIndex();
        if (selectIndex == -1) {
            deleteTeacherButton.setEnabled(false);
            upButton.setEnabled(false);
            downButton.setEnabled(false);
            nameTextField.setText("");
            idTextField.setText("");
            loginTextField.setText("");
        } else {
            deleteTeacherButton.setEnabled(true);
            upButton.setEnabled(true);
            downButton.setEnabled(true);
            if (selectIndex == 0) {
                upButton.setEnabled(false);
            }
            if (selectIndex == teacherList.getModel().getSize() - 1) {
                downButton.setEnabled(false);
            }
            Teacher t = (Teacher) teacherList.getSelectedValue();
            nameTextField.setText(t.getName());
            idTextField.setText(t.getId());
            loginTextField.setText(t.getLogin());
        }
    }//GEN-LAST:event_teacherListValueChanged

    private void subListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subListValueChanged
        // TODO add your handling code here:
        int selectIndex = subList.getSelectedIndex();
        if (selectIndex == -1) {
            deleteSubButton.setEnabled(false);
            subTextField.setText("");
            subIdTextField.setText("");
        } else {
            deleteSubButton.setEnabled(true);
            subTextField.setText(subjects.get(selectIndex).getName());
            subIdTextField.setText(subjects.get(selectIndex).getId());
        }
    }//GEN-LAST:event_subListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubButton;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JTabbedPane adminTabbedPane;
    private javax.swing.JButton deleteSubButton;
    private javax.swing.JButton deleteTeacherButton;
    private javax.swing.JButton downButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton passwdButton;
    private javax.swing.JLabel subIdLabel;
    private javax.swing.JTextField subIdTextField;
    private javax.swing.JLabel subLabel;
    private javax.swing.JList subList;
    private javax.swing.JPanel subPanel;
    private javax.swing.JScrollPane subScrollPane;
    private javax.swing.JTextField subTextField;
    private javax.swing.JList teacherList;
    private javax.swing.JPanel teacherPanel;
    private javax.swing.JScrollPane teacherScrollPane;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Teacher> teachers;
    private ArrayList<Subject> subjects;
}
