/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ARMSOutput.java
 *
 * Created on Mar 16, 2010, 1:15:00 AM
 */
package arms;

import org.jdesktop.application.Action;

/**
 *
 * @author vh4x0r
 */
public class ARMSOutput extends javax.swing.JFrame {

    /** Creates new form ARMSOutput */
    public ARMSOutput(int[] index) {
        this.index = index;
        initComponents();
    }

    @Action
    public void logout() {
        ARMSApp.getApplication().getMainFrame().setVisible(true);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subScrollPane = new javax.swing.JScrollPane();
        subList = new javax.swing.JList();
        teacherLabel = new javax.swing.JLabel();
        teacherScrollPane = new javax.swing.JScrollPane();
        teacherTextArea = new javax.swing.JTextArea();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getResourceMap(ARMSOutput.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N

        subScrollPane.setName("subScrollPane"); // NOI18N

        subList.setModel(new javax.swing.AbstractListModel() {
            Object[] strings = ARMSManager.getSubjects().toArray();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subList.setName("subList"); // NOI18N
        subList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subListValueChanged(evt);
            }
        });
        subScrollPane.setViewportView(subList);

        teacherLabel.setText(resourceMap.getString("teacherLabel.text")); // NOI18N
        teacherLabel.setName("teacherLabel"); // NOI18N

        teacherScrollPane.setName("teacherScrollPane"); // NOI18N

        teacherTextArea.setColumns(20);
        teacherTextArea.setRows(5);
        teacherTextArea.setName("teacherTextArea"); // NOI18N
        teacherScrollPane.setViewportView(teacherTextArea);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getActionMap(ARMSOutput.class, this);
        logoutButton.setAction(actionMap.get("logout")); // NOI18N
        logoutButton.setText(resourceMap.getString("logoutButton.text")); // NOI18N
        logoutButton.setName("logoutButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(teacherLabel)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(teacherScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(teacherLabel)
                        .addGap(18, 18, 18)
                        .addComponent(teacherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subListValueChanged
        // TODO add your handling code here:
        if (subList.isSelectionEmpty()) {
            return;
        }
        String text;
        if (index[subList.getSelectedIndex()] == -1) {
            text = "Teacher not allocated";
        } else {
            text = ARMSManager.getTeacher(index[subList.getSelectedIndex()]);
        }
        teacherTextArea.setText(text);
    }//GEN-LAST:event_subListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutButton;
    private javax.swing.JList subList;
    private javax.swing.JScrollPane subScrollPane;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JScrollPane teacherScrollPane;
    private javax.swing.JTextArea teacherTextArea;
    // End of variables declaration//GEN-END:variables
    private int[] index;
}
