/*
 * Automatic Routine Management System
 */

/*
 * TeacherForm.java
 *
 * Created on Mar 11, 2010, 12:32:57 AM
 */
package arms;

import java.util.Date;
import org.jdesktop.application.Action;

/**
 *
 * @author vh4x0r
 */
public class TeacherForm extends javax.swing.JFrame {

    /** Creates new form TeacherForm */
    public TeacherForm(Teacher t) {
        teacher = t;
        initComponents();
    }

    @Override
    public void dispose() {
        teacher.setLogin(new Date());
        ARMSApp.getApplication().getMainFrame().setVisible(true);
        super.dispose();
    }

    @Action
    public void logout() {
        dispose();
    }

    @Action
    public void moveUp() {
        teacher.moveUp(subSelectList.getSelectedIndex());
        subSelectList.setListData(teacher.getSubjectList().toArray());
    }

    @Action
    public void moveDown() {
        teacher.moveDown(subSelectList.getSelectedIndex());
        subSelectList.setListData(teacher.getSubjectList().toArray());
    }

    @Action
    public void remove() {
        teacher.removeSubject(subSelectList.getSelectedIndex());
        subList.setListData(ARMSManager.getAvailSubjectList(teacher.getSubjectList()).toArray());
        subSelectList.setListData(teacher.getSubjectList().toArray());
    }

    @Action
    public void add() {
        teacher.addSubject(ARMSManager.getAvailSubjectList(teacher.getSubjectList()).get(subList.getSelectedIndex()));
        subSelectList.setListData(teacher.getSubjectList().toArray());
        subList.setListData(ARMSManager.getAvailSubjectList(teacher.getSubjectList()).toArray());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        subSelectScrollPane = new javax.swing.JScrollPane();
        subSelectList = new javax.swing.JList();
        subListScrollPane = new javax.swing.JScrollPane();
        subList = new javax.swing.JList();
        upButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getResourceMap(TeacherForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N
        setResizable(false);

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        loginLabel.setText(resourceMap.getString("loginLabel.text")); // NOI18N
        loginLabel.setName("loginLabel"); // NOI18N

        subSelectScrollPane.setName("subSelectScrollPane"); // NOI18N

        subSelectList.setModel(new javax.swing.AbstractListModel() {
            Object[] strings = teacher.getSubjectList().toArray();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subSelectList.setName("subSelectList"); // NOI18N
        subSelectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subSelectListValueChanged(evt);
            }
        });
        subSelectScrollPane.setViewportView(subSelectList);

        subListScrollPane.setName("subListScrollPane"); // NOI18N

        subList.setModel(new javax.swing.AbstractListModel() {
            Object[] strings = ARMSManager.getAvailSubjectList(teacher.getSubjectList()).toArray();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subList.setName("subList"); // NOI18N
        subList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subListValueChanged(evt);
            }
        });
        subListScrollPane.setViewportView(subList);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(arms.ARMSApp.class).getContext().getActionMap(TeacherForm.class, this);
        upButton.setAction(actionMap.get("moveUp")); // NOI18N
        upButton.setText(resourceMap.getString("upButton.text")); // NOI18N
        upButton.setName("upButton"); // NOI18N
        upButton.setEnabled(false);

        removeButton.setAction(actionMap.get("remove")); // NOI18N
        removeButton.setText(resourceMap.getString("removeButton.text")); // NOI18N
        removeButton.setName("removeButton"); // NOI18N
        removeButton.setEnabled(false);

        downButton.setAction(actionMap.get("moveDown")); // NOI18N
        downButton.setText(resourceMap.getString("downButton.text")); // NOI18N
        downButton.setName("downButton"); // NOI18N
        downButton.setEnabled(false);

        addButton.setAction(actionMap.get("add")); // NOI18N
        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        addButton.setEnabled(false);

        logoutButton.setAction(actionMap.get("logout")); // NOI18N
        logoutButton.setText(resourceMap.getString("logoutButton.text")); // NOI18N
        logoutButton.setName("logoutButton"); // NOI18N

        nameTextField.setEditable(false);
        nameTextField.setText(teacher.getName());
        nameTextField.setBorder(null);
        nameTextField.setName("nameTextField"); // NOI18N

        loginTextField.setEditable(false);
        loginTextField.setText(teacher.getLogin());
        loginTextField.setBorder(null);
        loginTextField.setName("loginTextField"); // NOI18N

        idLabel.setText(resourceMap.getString("idLabel.text")); // NOI18N
        idLabel.setName("idLabel"); // NOI18N

        idTextField.setEditable(false);
        idTextField.setText(teacher.getId());
        idTextField.setBorder(null);
        idTextField.setName("idTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subSelectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(upButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(downButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, downButton, logoutButton, removeButton, upButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {subListScrollPane, subSelectScrollPane});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(upButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeButton)
                            .addComponent(addButton))
                        .addGap(18, 18, 18)
                        .addComponent(downButton)
                        .addGap(120, 120, 120)
                        .addComponent(logoutButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subSelectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addButton, downButton, logoutButton, removeButton, upButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {subListScrollPane, subSelectScrollPane});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subSelectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subSelectListValueChanged
        // TODO add your handling code here:
        int selectIndex = subSelectList.getSelectedIndex();
        if (selectIndex == -1) {
            removeButton.setEnabled(false);
            upButton.setEnabled(false);
            downButton.setEnabled(false);
        } else {
            removeButton.setEnabled(true);
            upButton.setEnabled(true);
            downButton.setEnabled(true);
            if (selectIndex == 0) {
                upButton.setEnabled(false);
            }
            if (selectIndex == subSelectList.getModel().getSize() - 1) {
                downButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_subSelectListValueChanged

    private void subListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subListValueChanged
        // TODO add your handling code here:
        addButton.setEnabled(!subList.isSelectionEmpty());
    }//GEN-LAST:event_subListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton downButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JList subList;
    private javax.swing.JScrollPane subListScrollPane;
    private javax.swing.JList subSelectList;
    private javax.swing.JScrollPane subSelectScrollPane;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
    private Teacher teacher;
}
